# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scholar-api-stg
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: scholar-api-stg
  template:
    metadata:
      labels:
        app: scholar-api-stg
    spec:
      containers:
      - name:  scholar-api-stg
        image: registry.polygram-solutions.com/scholar-api-stg:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: my-secret
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: scholar-api-stg
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: scholar-api-stg
